"""empty message

Revision ID: 1af16c152bf1
Revises: 3436e17f67c8
Create Date: 2016-01-13 06:42:15.012888

"""

# revision identifiers, used by Alembic.
revision = '1af16c152bf1'
down_revision = '3436e17f67c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('age', table_name='user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('age', 'user', ['age'], unique=True)
    ### end Alembic commands ###
