"""empty message

Revision ID: e180a9ab2498
Revises: 3f5359214057
Create Date: 2016-01-15 04:45:33.293176

"""

# revision identifiers, used by Alembic.
revision = 'e180a9ab2498'
down_revision = '3f5359214057'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('room', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'room')
    ### end Alembic commands ###
